services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smf-app
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/var/www/.env
      - ./database:/var/www/database
    env_file:
      - .env
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/faktury.sqlite
      TESSERACT_PATH: tesseract
    command: >
      sh -c "
      php artisan key:generate --force &&
      php artisan migrate --force &&
      php artisan db:seed --force &&
      php artisan serve --host=0.0.0.0 --port=8000
      "