services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smf-app
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./.env:/var/www/.env
      - ./database:/var/www/database
    env_file:
      - .env
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/faktury.sqlite
      TESSERACT_PATH: tesseract
    command: >
      sh -c "
      mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views bootstrap/cache database &&
      chmod -R 775 storage bootstrap/cache database &&
      php artisan key:generate --force &&
      php artisan config:clear &&
      php artisan migrate:fresh --seed --force &&
      php artisan serve --host=0.0.0.0 --port=8000
      "